"""add updated_at to integrations

Revision ID: 8cf0ee24ddb7
Revises: ac51faf20522
Create Date: 2026-07-27 04:53:54.603709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf0ee24ddb7'
down_revision: Union[str, Sequence[str], None] = 'ac51faf20522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # 1. Add the column as nullable first
    op.add_column(
        'integrations',
        sa.Column('updated_at', sa.DateTime(), nullable=True)
    )

    # 2. Give existing rows an updated_at value
    op.execute(
        "UPDATE integrations SET updated_at = created_at "
        "WHERE updated_at IS NULL"
    )

    # 3. Make the column NOT NULL
    op.alter_column(
        'integrations',
        'updated_at',
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integrations', 'updated_at')
    # ### end Alembic commands ###
