"""add error category and severity to integration runs

Revision ID: fc9879dff690
Revises: 10a1a79cab52
Create Date: 2026-07-29 12:40:07.050118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc9879dff690'
down_revision: Union[str, Sequence[str], None] = '10a1a79cab52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration_runs', sa.Column('error_category', sa.String(length=100), nullable=True))
    op.add_column('integration_runs', sa.Column('severity', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration_runs', 'severity')
    op.drop_column('integration_runs', 'error_category')
    # ### end Alembic commands ###
